BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EGB_OZKTYPES" (
	"ENUMERATION"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT UNIQUE,
	PRIMARY KEY("ENUMERATION")
);
CREATE TABLE IF NOT EXISTS "EGB_OZUTYPES" (
	"ENUMERATION"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("ENUMERATION")
);
CREATE TABLE IF NOT EXISTS "INW_PJ_GATUNKI" (
	"ID"	INTEGER NOT NULL,
	"SKROT"	TEXT UNIQUE,
	"NAZWA_PL"	TEXT NOT NULL,
	"NAZWA_LAC"	TEXT,
	"IGLASTE"	INTEGER NOT NULL DEFAULT 0 CHECK("IGLASTE" IN (0, 1, 2)),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "INW_PJ_KLASY_GR" (
	"ID"	INTEGER NOT NULL,
	"KLASA"	TEXT NOT NULL UNIQUE,
	"MIN"	INTEGER NOT NULL,
	"MAX"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "INW_PJ_POMIARY" (
	"ID"	INTEGER NOT NULL,
	"NUMER_DZ"	TEXT NOT NULL UNIQUE,
	"ODDZIAL"	TEXT,
	"LOKALIZACJA"	TEXT NOT NULL,
	"JEDN_REJESTROWA"	TEXT,
	"ADRES_LESNY"	TEXT,
	"OZU"	TEXT NOT NULL DEFAULT 'Ls',
	"OZK"	TEXT,
	"CREATED_BY"	TEXT NOT NULL DEFAULT USER,
	"CREATED_DATE"	DATE NOT NULL DEFAULT SYSDATE,
	FOREIGN KEY("OZU") REFERENCES "EGB_OZUTYPES"("ENUMERATION"),
	FOREIGN KEY("OZK") REFERENCES "EGB_OZKTYPES"("ENUMERATION"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "INW_PJ_DRZEWA" (
	"ID"	INTEGER NOT NULL,
	"POMIAR_ID"	INTEGER NOT NULL,
	"GATUNEK"	TEXT NOT NULL,
	"SREDNICA_130"	INTEGER NOT NULL CHECK("SREDNICA_130" < "SREDNICA_10"),
	"SREDNICA_10"	NUMERIC NOT NULL,
	"WYSOKOSC"	NUMERIC NOT NULL DEFAULT 0,
	"OBWOD_130"	NUMERIC NOT NULL DEFAULT 0,
	"OBWOD_10"	NUMERIC NOT NULL DEFAULT 0,
	"SHAPE"	TEXT,
	"LOC_X"	NUMERIC NOT NULL,
	"LOC_Y"	NUMERIC NOT NULL,
	FOREIGN KEY("POMIAR_ID") REFERENCES "INW_PJ_POMIARY"("ID"),
	FOREIGN KEY("GATUNEK") REFERENCES "INW_PJ_GATUNKI"("SKROT"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('I',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('II',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('III',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('IIIa',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('IIIb',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('IV',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('IVa',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('IVb',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('V',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('VI',NULL);
INSERT INTO "EGB_OZKTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('VIz',NULL);

INSERT INTO "EGB_OZUTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('R','gruntOrny');
INSERT INTO "EGB_OZUTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('L','lakaTrwala');
INSERT INTO "EGB_OZUTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('Ps','pastwiskoTrwale');
INSERT INTO "EGB_OZUTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('Ls','Las');
INSERT INTO "EGB_OZUTYPES" ("ENUMERATION","DESCRIPTION") VALUES ('Lz','gruntZadrzewionyIZakrzewiony');

INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (1,'Św','Swierk pospolity','Picea abies',1);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (2,'Jd','Jodla pospolita','Abies alba',1);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (3,'Bk','Buk zwyczajny','Fagus sylvatica',0);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (4,'So','Sosna zwyczajna','Pinus sylvestris',1);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (5,'Db2','Dab bezszypulkowy','Quercus petraea',0);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (6,'Db1','Dab szypulkowy','Quercus robur',0);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (7,'Jw','Klon jawor','Acer pseudoplatanus',0);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (8,'Brz','Brzoza brodawkowata','Betula pendula',0);
INSERT INTO "INW_PJ_GATUNKI" ("ID","SKROT","NAZWA_PL","NAZWA_LAC","IGLASTE") VALUES (9,'Md','Modrzew europejski','Larix decidua',1);

INSERT INTO "INW_PJ_KLASY_GR" ("ID","KLASA","MIN","MAX") VALUES (1,'I',7,15);
INSERT INTO "INW_PJ_KLASY_GR" ("ID","KLASA","MIN","MAX") VALUES (2,'II',16,35);
INSERT INTO "INW_PJ_KLASY_GR" ("ID","KLASA","MIN","MAX") VALUES (3,'III',36,55);
INSERT INTO "INW_PJ_KLASY_GR" ("ID","KLASA","MIN","MAX") VALUES (4,'IV',56,75);
INSERT INTO "INW_PJ_KLASY_GR" ("ID","KLASA","MIN","MAX") VALUES (5,'V',76,95);

CREATE UNIQUE INDEX IF NOT EXISTS "EGB_OZKTYPES_PK" ON "EGB_OZKTYPES" (
	"ENUMERATION"
);
CREATE UNIQUE INDEX IF NOT EXISTS "EGB_OZKTYPES_UK1" ON "EGB_OZKTYPES" (
	"DESCRIPTION"
);
CREATE UNIQUE INDEX IF NOT EXISTS "EGB_OZUTYPES_PK" ON "EGB_OZUTYPES" (
	"ENUMERATION"
);
CREATE UNIQUE INDEX IF NOT EXISTS "EGB_OZUTYPES_UK1" ON "EGB_OZUTYPES" (
	"DESCRIPTION"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_GATUNKI_PK" ON "INW_PJ_GATUNKI" (
	"ID"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_GATUNKI_UK1" ON "INW_PJ_GATUNKI" (
	"SKROT"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_KLASY_GR_PK" ON "INW_PJ_KLASY_GR" (
	"ID"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_KLASY_GR_UK1" ON "INW_PJ_KLASY_GR" (
	"KLASA"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_POMIARY_PK" ON "INW_PJ_POMIARY" (
	"ID"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_POMIARY_UK1" ON "INW_PJ_POMIARY" (
	"NUMER_DZ"
);
CREATE UNIQUE INDEX IF NOT EXISTS "INW_PJ_DRZEWA_PK" ON "INW_PJ_DRZEWA" (
	"ID"
);
CREATE VIEW INW_PJ_POMIARY_DEV_V AS 
  select
 p.NUMER_DZ,
 p.LOKALIZACJA, 
 p.ODDZIAL, 
 p.JEDN_REJESTROWA, 
 p.ADRES_LESNY, 
 p.OZU || IFNULL(p.OZK, '') as UZYTEK, 
 o.DESCRIPTION as OZU, 
 d.GATUNEK,
 g.NAZWA_PL, 
 g.NAZWA_LAC, 
 g.IGLASTE, 
 d.SREDNICA_130,
 d.SREDNICA_10,
 d.WYSOKOSC, 
 d.OBWOD_130, 
 d.OBWOD_10, 
 d.LOC_X || ' ' || d.LOC_Y as wkt, 
 p.CREATED_DATE,
 p.CREATED_BY
from
    INW_PJ_DRZEWA d
join INW_PJ_POMIARY p on d.POMIAR_ID = p.ID
join INW_PJ_GATUNKI g on d.GATUNEK = g.SKROT
left outer join EGB_OZUTYPES o on p.OZU = o.ENUMERATION;
